### ISSUE TITLE
Suggestions for its Web Interface

### ISSUE THREAD

**Issue by Zero3K** [synappnz/ipright#2]
1. It could be made easier to use.
2. Its not showing up properly on Opera 12.16.

**Comment by synappnz** [comment]
1. What could be done to make it easier?
2. Fixed.

**Comment by Zero3K** [comment]
1. I just think it could be made nicer looking. Right now it looks too basic. Also, maybe some explanations for the options could be added via a pop-up html page.

**Comment by synappnz** [comment]
UI updated.

**Comment by Zero3K** [comment]
Thanks for doing that.
